iastate_theme.settings:
  type: theme_settings
  label: 'Iowa State Theme Settings'
  mapping:
    isu_navbar:
      type: integer
      label: 'Show ISU navbar'
    gold_border_hidden:
      type: integer
      label: 'Show gold border'
    features:
      type: mapping
      label: 'Optional features'
      mapping:
        favicon:
          type: boolean
          label: 'Use the favicon supplied by the theme'
    default_copyright:
      type: boolean
      label: 'Use the defaults supplied by the theme'
    copyright_subject:
      type: string
      label: 'Subject of copyright'
    default_site_logo_alttext_url:
      type: boolean
      label: 'Use the defaults supplied by the theme'
    site_logo_alttext:
      type: string
      label: 'Text describing image'
    site_logo_url:
      type: uri
      label: 'URL attribute'
    default_footer_logo:
      type: boolean
      label: 'Use the defaults supplied by the theme'
    iastate_footer_logo_path:
      type: uri
      label: 'Path to custom footer logo'
    iastate_footer_logo_alttext:
      type: string
      label: 'Text describing image'
    iastate_footer_logo_url:
      type: uri
      label: 'Custom footer logo url'
    iastate_contact_address:
      type: text
      label: 'Address'
    iastate_contact_email:
      type: email
      label: 'Email'
    iastate_contact_phone:
      type: string
      label: 'Phone'
    iastate_associate1_title:
      type: string
      label: 'Associate 1 Title'
    iastate_associate1_url:
      type: uri
      label: 'Associate 1 URL'
    iastate_associate2_title:
      type: string
      label: 'Associate 2 Title'
    iastate_associate2_url:
      type: uri
      label: 'Associate 2 URL'
    iastate_associate3_title:
      type: string
      label: 'Associate 3 Title'
    iastate_associate3_url:
      type: uri
      label: 'Associate 3 URL'
    iastate_associate4_title:
      type: string
      label: 'Associate 4 Title'
    iastate_associate4_url:
      type: uri
      label: 'Associate 4 URL'
    iastate_associate5_title:
      type: string
      label: 'Associate 5 Title'
    iastate_associate5_url:
      type: uri
      label: 'Associate 5 URL'
    iastate_associate6_title:
      type: string
      label: 'Associate 6 Title'
    iastate_associate6_url:
      type: uri
      label: 'Associate 6 URL'
    default_social_footer:
      type: boolean
      label: 'Show social media footer links block'

